[package]
name = "lockchain-provider"
version = "0.2.1"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"], optional = true }
schemars = { version = "0.8", features = ["derive"], optional = true }

[features]
serde = ["dep:serde"]
schema = ["dep:schemars", "serde"]
