[package]
name = "lockchain-zfs"
version = "0.2.1"
edition = "2021"

[dependencies]
lockchain-core = { path = "../lockchain-core" }
lockchain-provider = { path = "../lockchain-provider" }
log = "0.4"

[dev-dependencies]
tempfile = "3"
sha2 = "0.10"
hex = "0.4"
